# Generated by Django 2.2.3 on 2019-07-03 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.CharField(max_length=100, null=True, verbose_name='Book')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=30, null=True, verbose_name='Student Name')),
                ('photo', models.ImageField(upload_to='static/img/1.jpg')),
                ('department', models.CharField(blank=True, choices=[('ise', 'info science'), ('mh', 'mech'), ('cv', 'civil'), ('bt', 'biotech')], max_length=30, null=True, verbose_name='Department')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('section', models.CharField(blank=True, choices=[('a', 'A'), ('b', 'B'), ('c', 'C')], max_length=10, null=True, verbose_name='Section')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher', models.CharField(max_length=100, verbose_name='Teacher Name')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sectionn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sectionn', models.CharField(max_length=20, verbose_name='Sectionn')),
                ('advisor', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Teacher')),
                ('students', models.ManyToManyField(to='home.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libraby_name', models.CharField(max_length=100, null=True, verbose_name='Library')),
                ('books', models.ManyToManyField(null=True, to='home.Book')),
            ],
        ),
    ]
